config:
  target: 'http://localhost:8080'
  phases:
    - duration: 10
      arrivalRate: 500
      name: Sustained 500 users for 10 seconds
scenarios:
  - flow:
      - get:
          url: '/carts/3'
